### ISSUE TITLE
/var/lib/emby-server symlink

### ISSUE THREAD

**Issue by brianjmurrell** [Wuerfelbecher/jellyfin-rpm#3]
It seems that the database(s) have fully-qualified paths in them, so when migrating databases from Emby to Jellyfin, once they have been copied to `/var/lib/jellyfin/` they will still refer to data/files in `/var/lib/emby-server/`.

I would suggest that if `/var/lib/emby-server/` doesn't already exist, indicating that this is an installation on a machine without an existing Emby installation, that a convenience symlink be created for those that want to then copy their database and files from a different Emby machine.

If the `/var/lib/emby-server/` directory does exist, it's a side-by-side install and once the database(s) are copied into `/var/lib/jellyfin/` the existing `/var/lib/emby-server/` paths will just work.

**Comment by Wuerfelbecher** [comment]
Im not really sure how to do that in an RPM, i could print mesages if `/var/lib/emy-server` exists to inform the user about this.

But isn't it better to just fix the DB?
Maybe something like this (im no SQL expert) for all the tables?

```sql
UPDATE item
SET path=REPLACE(path, '/var/lib/emby-server', '/var/lib/emby-server');
```

**Comment by brianjmurrell** [comment]
> Im not really sure how to do that in an RPM,

Create a symlink?  `ln -s ...` in `%post`, wrapped with some logic about when to do it and when not to.

> i could print mesages if `/var/lib/emy-server` exists to inform the user about this.

Yeah.  That works to, but is a bit more error prone.
 
> But isn't it better to just fix the DB?

Sure.  That's jellyfin/jellyfin#404.  But is a bit more work.

> Maybe something like this (im no SQL expert) for all the tables?
> 
> ```sql
> UPDATE item
> SET path=REPLACE(path, '/var/lib/emby-server', '/var/lib/emby-server');
> ```

I'm no SQL expert either, so I don't know if that's the right formula or not.

The symlink works.  I'm using it here.

**Comment by Wuerfelbecher** [comment]
I would prefer a clean switch instead of symlinking, so followed my SQL update idea and got jellyfin working with my emby database after updating the DB, all my libraries where there and i could play it back as expected.

After dumping the DBs and searching for `/var/lib/emby-server` i only found hardcoded paths  in the `library.db` so here is what i used:
```shell
#!/bin/sh
db=${1:-/var/lib/jellyfin/data/library.db}
embypath=${2:-/var/lib/emby-server}
jellyfinpath=${3:-/var/lib/jellyfin}
sqlite3 ${db} << SQL
UPDATE Chapters2 
SET ImagePath=REPLACE(ImagePath, '${embypath}', '${jellyfinpath}');
UPDATE TypedBaseItems 
SET Path=REPLACE(Path, '${embypath}', '${jellyfinpath}');
UPDATE TypedBaseItems 
SET data=REPLACE(data, '${embypath}', '${jellyfinpath}');
SQL
```

I included the script in the RPM and and added a note in the README about fixing the database after copying.
