### ISSUE TITLE
10.0.2?

### ISSUE THREAD

**Issue by brianjmurrell** [Wuerfelbecher/jellyfin-rpm#8]
Jellyfin [10.0.2](https://github.com/jellyfin/jellyfin/commits/v10.0.2) was released but without the new RPM building support in it yet.

Can you publish a 10.0.2 RPM to COPR from here, please?  :-)

**Comment by Wuerfelbecher** [comment]
Sure let me check if there any changes in the Debian package that impact my RPM package.

**Comment by Wuerfelbecher** [comment]
Everything looks good so i pushed a new build to COPR.
